### ISSUE TITLE
ckanext_multilang throws an IntegrityError error in the datastore create API endpoint

### ISSUE THREAD

**Issue by abulojoshua1** [geosolutions-it/ckanext-faoclh#99]
ckanext_multilang throws an integrity error during the creation of a new datastore resource using the datastore create API endpoint (`/api/3/action/datastore_create`).

###### Error stack trace
```
IntegrityError: (psycopg2.IntegrityError) null value in column "text" violates not-null constraint DETAIL: Failing row contains (85, f59bfc35-a852-4084-9297-891f632db1d0, name, en, null). [SQL: 'INSERT INTO resource_multilang (resource_id, field, lang, text) VALUES (%(resource_id)s, %(field)s, %(lang)s, %(text)s) RETURNING resource_multilang.id'] [parameters: {'lang': u'en', 'text': None, 'resource_id': u'f59bfc35-a852-4084-9297-891f632db1d0', 'field': 'name'}]
```

###### Steps to reproduce
- Activate the virtualenv using `. /usr/lib/ckan/default/bin/activate`
- Install [ckanext-multilang](https://github.com/geosolutions-it/ckanext-multilang)
- Configuare CKAN's datastore by following the steps in the [documentation](https://docs.ckan.org/en/2.8/maintaining/datastore.html)
- Login on CKAN and navigate to your profile page to get your API key (found at the bottom of the left side nav).
- Create a new package resource in the datastore using the POST datastore API endpoint (`/api/3/action/datastore_create`) with header `"Authorization: {YOUR-API-KEY}"` and the sample POST data below:
```
{
   "resource":{
      "package_id":"{PACKAGE-ID}"
   },
   "fields":[
      {
         "id":"lat"
      },
      {
         "id":"lon"
      }
   ],
   "records":[
      {
         "lat":29.297550000000115,
         "lon":"-25.086769999999831"
      },
      {
         "lat":29.297550000000115,
         "lon":"-25.086769999999831"
      }
   ]
}
```

**Comment by etj** [comment]
Confirmed.

Running a 

    curl -i -XPOST -d @datastore.json http://127.0.0.1:5000/api/3/action/datastore_create -H "Authorization: YOUR_AUTH_KEY"

with the file `datastore.json` containing the json in the issue description raises this exception:

```
2020-07-29 10:40:50,416 DEBUG [ckanext.multilang.plugin] ...Creating index for Package localized field: title - en
2020-07-29 10:40:50,416 DEBUG [ckanext.multilang.plugin] Index successfully created for Package: u'test 3'
2020-07-29 10:40:50,416 DEBUG [ckanext.multilang.plugin] ...Creating index for Package localized field: notes - en
2020-07-29 10:40:50,416 DEBUG [ckanext.multilang.plugin] Index successfully created for Package: u'Test con datastore'
2020-07-29 10:40:51,177 INFO  [ckanext.multilang.plugin] Localised fields are missing in resource_multilang table, persisting ...
2020-07-29 10:40:51,180 ERROR [ckanext.multilang.model.package_multilang] Exception occurred while persisting DB objects: (psycopg2.IntegrityError) null value in column "text" violates not-null constraint
DETAIL:  Failing row contains (9, 3c4288c4-2483-4fd0-ab11-0f8b615d8436, name, en, null).
 [SQL: 'INSERT INTO resource_multilang (resource_id, field, lang, text) VALUES (%(resource_id)s, %(field)s, %(lang)s, %(text)s) RETURNING resource_multilang.id'] [parameters: {'lang': u'en', 'text': None, 'resource_id': u'3c4288c4-2483-4fd0-ab11-0f8b615d8436', 'field': 'name'}]
2020-07-29 10:40:51,180 ERROR [ckan.views.api] (psycopg2.IntegrityError) null value in column "text" violates not-null constraint
DETAIL:  Failing row contains (9, 3c4288c4-2483-4fd0-ab11-0f8b615d8436, name, en, null).
 [SQL: 'INSERT INTO resource_multilang (resource_id, field, lang, text) VALUES (%(resource_id)s, %(field)s, %(lang)s, %(text)s) RETURNING resource_multilang.id'] [parameters: {'lang': u'en', 'text': None, 'resource_id': u'3c4288c4-2483-4fd0-ab11-0f8b615d8436', 'field': 'name'}]
Traceback (most recent call last):
  File "/home/etj/prj/ckan/faoclh/ckan/ckan/views/api.py", line 288, in action
    result = function(context, request_data)
  File "/home/etj/prj/ckan/faoclh/ckan/ckan/logic/__init__.py", line 466, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/etj/prj/ckan/faoclh/ckan/ckanext/datastore/logic/action.py", line 116, in datastore_create
    context, data_dict['resource'])
  File "/home/etj/prj/ckan/faoclh/ckan/ckan/logic/__init__.py", line 466, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/etj/prj/ckan/faoclh/ckan/ckan/logic/action/create.py", line 346, in resource_create
    plugin.after_create(context, resource)
  File "/home/etj/prj/ckan/faoclh/ckanext-multilang/ckanext/multilang/plugin.py", line 288, in after_create
    ResourceMultilang.persist(resource, lang)
  File "/home/etj/prj/ckan/faoclh/ckanext-multilang/ckanext/multilang/model/package_multilang.py", line 254, in persist
    session.commit()
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 430, in _prepare_impl
    self.session.dispatch.before_commit(self.session)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/home/etj/prj/ckan/faoclh/ckan/ckan/model/meta.py", line 55, in before_commit
    session.flush()
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/etj/prj/ckan/faoclh/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (psycopg2.IntegrityError) null value in column "text" violates not-null constraint
DETAIL:  Failing row contains (9, 3c4288c4-2483-4fd0-ab11-0f8b615d8436, name, en, null).
 [SQL: 'INSERT INTO resource_multilang (resource_id, field, lang, text) VALUES (%(resource_id)s, %(field)s, %(lang)s, %(text)s) RETURNING resource_multilang.id'] [parameters: {'lang': u'en', 'text': None, 'resource_id': u'3c4288c4-2483-4fd0-ab11-0f8b615d8436', 'field': 'name'}]
```
